/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/exercises': typeof ExercisesRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/copilot'
    | '/emergency'
    | '/exercises'
    | '/insights'
    | '/journey'
    | '/medications'
    | '/profile'
    | '/records'
    | '/settings'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/copilot'
    | '/emergency'
    | '/exercises'
    | '/insights'
    | '/journey'
    | '/medications'
    | '/profile'
    | '/records'
    | '/settings'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/copilot'
    | '/emergency'
    | '/exercises'
    | '/insights'
    | '/journey'
    | '/medications'
    | '/profile'
    | '/records'
    | '/settings'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CopilotRoute: typeof CopilotRoute
  EmergencyRoute: typeof EmergencyRoute
  ExercisesRoute: typeof ExercisesRoute
  InsightsRoute: typeof InsightsRoute
  JourneyRoute: typeof JourneyRoute
  MedicationsRoute: typeof MedicationsRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  CopilotRoute: CopilotRoute,
  EmergencyRoute: EmergencyRoute,
  ExercisesRoute: ExercisesRoute,
  InsightsRoute: InsightsRoute,
  JourneyRoute: JourneyRoute,
  MedicationsRoute: MedicationsRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
